[package]
name = "godot_enums"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" }
num = "0.4"
num-derive = "0.4"
num-traits = "0.2"
syn = "2.0"
quote = "1.0"
